### ISSUE TITLE
Updating caused sddm to be reenabled,started, and its tty focused

### ISSUE THREAD

**Issue by michaelmrose** [project-trident/trident-core#104]
I switched to lightdm among other reasons because sddm froze a few times and failed to recognize i3-wm as an available session. I disabled sddm by removing its symlink in /var/service when running xbps-install -Su to update packages it was surprising to me re enabled, started, and I was switched to its tty which was pretty confusing.

Thanks for all your efforts!

**Comment by beanpole135** [comment]
This is intentional as a basic functionality of the "trident-desktop" package to ensure that all the required services (such as sddm) are enabled after an upgrade.

If you are switching all of the "desktop" functionality around to other login managers or desktop environments, I highly recommend removing the "trident-desktop" meta-package from your system to prevent this issue in the future - since you are basically trying to disable that package after-the-fact anyway.
