### ISSUE TITLE
Add lines to /etc/pam.d/lightdm to enable lightdm to mount encrpyted user dir

### ISSUE THREAD

**Issue by michaelmrose** [project-trident/trident-core#105]
**Is your feature request related to a problem? Please describe.**
I prefer lightdm to sddm and would prefer it worked with zfscrypt

**Describe the solution you'd like**
Adding the following lines makes it work correctly

auth include system-login
account include system-login
session include system-login

**Describe alternatives you've considered**
The obvious alternative is to use sddm however sddm on trident uses a non standard session dir meaning that installing say i3-wm using the gui to select session type appears from the user perspective to be completely broken although you can fix this by copying over the desktop file to the dir used by sddm. Presumably this is also true of the 1001 different graphical environments available for lights. Configuring lightdm to run correctly just requires adding the same lines to the pam configuration that is included in the sddm file.

Personally I've been bitten by several bugs specifically with sddm in the past I don't consider it reliable software.

**Comment by beanpole135** [comment]
Couple quick issues with this:
1. Trident does not use/provide/recommend lightdm. We setup SDDM and have that already running just fine.
2. The issue you want fixed is that the lightdm PAM config file is not using the "system-login" rules on Void. That would need to be fixed in the lightdm package for Void, not in Trident itself.

You might want to open up a bug report on https://github.com/void-linux/void-packages to get that PAM config file patched, or submit the patch yourself: https://github.com/void-linux/void-packages/tree/master/srcpkgs/lightdm
