### ISSUE TITLE
AppCafe - No Packages Found.

### ISSUE THREAD

**Issue by mrT55** [project-trident/trident-core#14]
I installed: Trident-x64-20180831.iso
ran:  trueos-update upgrade

SysAdm: AppCafe
   Click on any of the popular searches and get: No Packages Found.
   Same with setting it to 'Browsing: all'

**Comment by q5sys** [comment]
Thanks for the ticket.  We think we know the cuplrit for this, and we're working on it.

**Comment by beanpole135** [comment]
With TrueOS 18.06+ the `pkg` utility got moved into the base OS so all the dirs/paths that SysAdm is searching for the package repos are wrong now. We are still fixing/testing some changes to SysAdm which should allow it to find the repos again.

**Comment by beanpole135** [comment]
This has been fixed with RC1. The "AppCafe" within SysAdm can now probe/use all configured repositories once again. 
Note: It may take a few minutes after booting the system for the first time before the AppCafe will populate - the repositories need to be fetched/synced first after you get networking setup.
