### ISSUE TITLE
SysAdm missing update manager and boot environment manager

### ISSUE THREAD

**Issue by mrT55** [project-trident/trident-core#15]
I installed: Trident-x64-20180831.iso
ran:  trueos-update upgrade

SysAdm - missing update manager
         and     Boot Environment Manager

**Comment by beanpole135** [comment]
The boot environment manager has been fixed in SysAdm for the new location of the `beadm` utility (got moved into the base OS with TrueOS 18.06+).
The update manager is still disabled as the update utility (pc-updatemanager) was depricated in TrueOS 18.06 and replaced by a new tool (trueos-update).
Because of this, there will need to be a new API backend written up for using the new tool.

**Comment by RodMyers** [comment]
Boot Environment Manager installed in RC3

**Comment by beanpole135** [comment]
Finished.
A new update manager has been created for Project Trident and will be available with the upcoming RELEASE version of Project Trident.
