### ISSUE TITLE
Route through TOR won't connect at all.  All network traffic stops

### ISSUE THREAD

**Issue by Troub274** [project-trident/trident-core#46]
the route through TOR button on the network manager does not work.
pkg install TOR (it's missing during install)
If TOR is not installed the menu item should not show up.
However when TOR is installed after pressing the route through TOR
it launches the browser and won't connect.
No TCP traffic works, not pings not DNS nothing.
Uncheck the route through tor network and everything works again.
This has been a problem for 2 years and no one wants to fix it.

**Comment by Troub274** [comment]
by the way if you run TOR from the command line it works great and builds a circuit. However nothing will route through it.  So while tor is running if you press route through TOR once again nothing.

**Comment by Troub274** [comment]
expected behavior: if you run openvpn (or any vpn) then route through TOR it should send the tor traffic through the VPN.  This has never worked in TRUEOS but works great in linux or mac.  It is a "best practice" to route tor through a VPN first to hide that you are using TOR.

**Comment by RodMyers** [comment]
Tor is/was not installed. install tor

sudo plg install tor

and try again

**Comment by Troub274** [comment]
UM... it was.... actually.
It's dying in SOCAT.  DNS queries are redirected through socat to port 9530 but they are never making it there.
SOCAT drops an error Exactly 2 addresses required ( there are 0; use option "-h" for help.
Upon further examination it appears that socat is actually loosing data.  the packets are getting scrambled inside socat.
I tried to re-write it 2 years ago and failed so I gave up.
Steve

**Comment by RodMyers** [comment]
The menu item should be removed, until a later date to review or remove permanently.

**Comment by q5sys** [comment]
ok, lets step back and go through this one piece at a time.
a) Is Tor installed?
b) If Yes, does the menu item attempt to start Tor at all?
c) If Yes, does Tor start?
d) If Yes, do you connect to any other systems (even if a full circuit is not created)

Alternatively,
e) If the answer to b is no, does the menu item work if you manually start Tor on your own before using the menu?

Lastly,
Why are you bringing up expected behavior of Tor through a VPN when that's not what your ticket is about?  That's just complicating the matter with another step.  Go back to basics.  Disable your VPN, connect directly to your ISP and repeat the steps.

**Comment by RodMyers** [comment]
when enabling "route through tor" the /etc/resolv.conf file gets over written

i populated with my original, and was able to get on the web

hit https://check.torproject.org/    <-- stated was "Sorry, you are not using tor"

**Comment by beanpole135** [comment]
Closing this stale issue.
The Tor mode scripts were re-written a few months ago specifically for Project Trident and appear to be working fine now.
