### ISSUE TITLE
Wallpaper should be set to scale

### ISSUE THREAD

**Issue by revhelix** [project-trident/trident-core#5]
Switching from the original low resolution to 4K, the image should scale.
Low-ish priority issue.

**Comment by revhelix** [comment]
![scaleissue](https://user-images.githubusercontent.com/1694339/44939645-effd1980-ad54-11e8-83b0-40d8ba13ee18.jpg)

**Comment by beanpole135** [comment]
This has already been fixed in the updated version of the Lumina port (missing the auto-update of the background on screen change).
In the meantime, you can quickly bypass this issue by manually triggering a wallpaper refresh via the wallpaper settings (add or remove an item from the list and then save the changes).
