### ISSUE TITLE
Feature request: integration of wipe tool into Lumina-fm

### ISSUE THREAD

**Issue by q-pa** [project-trident/trident-core#51]
It would be cool for Lumina-fm to have a tool like e.g. BCWipe integrated with a menu entry to delete files with the default setting.

**Comment by q5sys** [comment]
Couple things...
1) BCWipe is commercial product so we can't use that one specifically.  But Im sure we could find a MIT/BSD licensed 'wiping' program out there.
However...
2) It would be effectively pointless on ZFS drives.  With the way ZFS works, there's no way to ever completely destroy your data.  That was the underlying drive for the FS.   And the ZFS devs have not been willing to entertain the idea of forensically being able to destroy your data on purpose.
Now you could use a 'wiping' utility on other formatted disks, but since the user is not informed of the FS of any particular disk... it's not really going to help.
I'd really rather not give the user the belief that they can 'wipe' data, when in fact in many situations they will not be able to.

I would recommend a 3rd party application if you're wanting to 'wipe' files on non-ZFS drives.
Thanks for the recommendation though.  If ZFS ever enabled some type of 'purge' functionality for metadata on ZFS formatted disks... we'll definitely be interested in making a feature like this possible.
