### ISSUE TITLE
[low] Trident images get scrunched during install when diagnostic/info panel open

### ISSUE THREAD

**Issue by revhelix** [project-trident/trident-core#7]
Trident images get scrunched during install when diagnostic/info panel open

**Comment by revhelix** [comment]
![scrunch](https://user-images.githubusercontent.com/1694339/44939854-75cd9480-ad56-11e8-8ee0-f07b06adcc5a.jpg)

**Comment by beanpole135** [comment]
FYI: This is a side effect of the wallpaper for the slide being put into the tab widget rather than changing the wallpaper for the main window itself.
Would need to find a way to programatically change the stylesheet for the main window in order for different pages to set different wallpaper images, as right now all the wallpapers/backgrounds are just inserted into the stylesheet within the mainUI.ui file.

**Comment by revhelix** [comment]
I figured as much, either way its an imperfection, so I complained =)

**Comment by RodMyers** [comment]
can you try the RELEASE ISO, and close if fixed?

**Comment by RodMyers** [comment]
closed with lack of reply
