### ISSUE TITLE
C compiler fails

### ISSUE THREAD

**Issue by SteveBH** [project-trident/trident-core#77]
Issue
The current default Trident is missing one of the following pkgs for the c compiler to work.

1. Go to https://discourse.trueos.org/t/u4-update-now-available/3637/3?u=nevets
2. It seems there is a need to install:
OS-Clang and/or
OD-clibs-development and/or
OS-libcompiler_rt-development
in the default Trident distribution.

**Expected behavior**
sudo make install of the lastest Curl [ftp] port from the TrueOS repo [git pull] should compile.

**OS Version:**
FreeBSD trident-4729 13.0-CURRENT FreeBSD 13.0-CURRENT GENERIC-NODEBUG  amd64

**Additional context**
The pkg audit showed 'curl' was vulnerable, AND, the TrueOS repo had the update - it just wasn't part of the same weeks' Triddent update. Hence the need to port the fix to curl. If the Trident updates contained the latest pkg audit fixes I'd wait for the Trident update rather than port the fix - just an observation, not a critisism.

**Comment by beanpole135** [comment]
The FreeBSD base package system is what determines the breakdown of all the development files into the OS-*-development packages.
Project Trident is a binary-update system (packages) rather than a source-based update system so the OS development packages are not needed as part of the base installation (although we ensure they are always available as desired). You just need to install those packages if you want to compile applications from source on a Project Trident system.

**Comment by SteveBH** [comment]
Thanks Ken, for the feedback. I'm a novice with BSD and the only time I consider porting is if a pkg fails audit for security vulnerability. If the fixed packages are made available reasonably quickly, I agree, there's no apparent requirement to port or need for the base system to contain the compilers.
