### ISSUE TITLE
Bios install fails

### ISSUE THREAD

**Issue by revhelix** [project-trident/trident-core#8]
Tested under VMware workstation 14.1.3 build-9474260 pro (linux)

BIOS reported that it couldn't find the bootloader
![missingbootloader](https://user-images.githubusercontent.com/1694339/44939540-1078a400-ad54-11e8-8ff0-7b0065354d94.jpg)

**Comment by revhelix** [comment]
EFI worked fine

**Comment by beanpole135** [comment]
I have just verified this same issue with BIOS install into VirtualBox as well:
Steps to reproduce:
1. Create a new VM (completely blank - no partition information or anything)
2. Install to the freespace on the disk
3. Post-install, virtualbox will boot into this same "no boot loader" message.

**Comment by beanpole135** [comment]
This appears to be fixed in BETA3 with a couple caveats:
1. If installing to a full disk (even a blank one), it will install the FreeBSD bootloader to the MBR on that disk.
2. If installing to a partition (or even the designated "free space" on a disk) rather than a full disk then it will **NOT** install the FreeBSD bootloader to the MBR on that disk. This is to prevent possibly breaking whichever bootloader you currently have installed into the MBR on that disk. Instead, there is a warning in the installer that you might need to update the MBR or register the new partition with your bootloader before it becomes available (GRUB in particular typically needs to have the config files updated for changes like this).
