### ISSUE TITLE
Unable to resize any window apart from Insight file manager

### ISSUE THREAD

**Issue by SAUCYSOUP76** [project-trident/trident-core#97]
**Describe the bug**
Open any window and unable to resize, apart from Insight file manager, changing themes or new account does not fix the issue.

However changing the window manager theme fixes the issue.
**To Reproduce**
1. Go to 'Start application'
2. Click on 'Icon in start menu'
3. Scroll down to 'corner of the window'
4. unable to resize any window apart from insight file manager

**Expected behavior**
Expect to resize window to desirable width and height
**Screenshots**
https://pasteboard.co/ISgvSGW.png
https://pasteboard.co/ISgw69e.png
https://pasteboard.co/ISgwqKs.png

(If screenshots become unavailable, screenshots + video made available to the trident telegram chat timestamp: 20:25 UK standard time dated 29th Jan 2020)

**OS Version:**
 - Typically the output from running `uname -a` within a terminal.
Linux Trident-8842 5.4.15_1 #1 SMP PREEMPT Sun Jan 26 13:28:15 UTC 2020 x86_64 GNU/Linux

**Additional context**
Using AMD hardware
CPU: AMD Ryzen 3 1200 (4) @ 3.100GHz
GPU: AMD ATI Radeon 540/540X/550/550X / RX 540X/550/550X

**Comment by beanpole135** [comment]
This is due to using the broken/fallback Fluxbox window theme by default on Void.
The release version of Trident on Void switches the default theme to one we created, but you can fix it on your own system right now simply by following these steps:

1. Open the desktop configuration utility (lumina-config)
2. Click on the "Window Manager" option in the "Appearance" category.
3. Change the "Window Theme" to something other than "arch" and save your change.
